version: '3.8'

services:
  node_backend:
    container_name: webbylab_movies_andrey
    image: webbylab_movies_andrey:0.0.2
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - EXTERNAL_PORT=8000
      - PGDATABASE=webbylab_movies_db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webbylab_movies_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
 nps_data: {}